---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: macosx-10.10
    driver:
      box: roboticcheese/macosx-10.10
      ssh:
        insert_key: false

suites:
  - name: default
    run_list:
      - recipe[vmware-fusion]
  - name: remove
    run_list:
      - recipe[vmware-fusion_test::remove]
