language: objective-c

branches:
  only:
    - master

install:
  - curl -L https://www.chef.io/chef/install.sh | sudo bash -s -- -P chefdk
  - chef exec bundle update

before_script:
  - cp .kitchen.travis.yml .kitchen.local.yml

script:
  - chef exec bundle exec rake && chef exec bundle exec kitchen test -c 2

after_script:

env:
  global:
